package ru.veider.multitimer.const


// Utils
const val TAG = "TAG"

// Service
val ALARM_CHANNEL_ID = "ALARM_CHANNEL_ID"
val SIMPLE_CHANNEL_ID = "SIMPLE_CHANNEL_ID"
val COUNTER_ID = "COUNTER_ID"
val COUNTER = "COUNTER"
val COUNTERS = "COUNTERS"
val EVENT = "EVENT"
val EVENT_BUTTON = "EVENT_BUTTON"
val EVENT_TIMER = "EVENT_TIMER"
val EVENT_STOP = "EVENT_STOP"
val EVENT_START = "EVENT_STOP"
